# ======================
# DATABASE
# ======================

spring.datasource.url=jdbc:mysql://localhost:3306/bce_alumni
spring.datasource.username=root
spring.datasource.password=root1234

# ======================
# JPA
# ======================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# SERVER
# ======================

server.port=8080

# ======================
# JWT
# ======================

jwt.secret=bceAlumniJwtSecretKeyForSpringBootProject2026SecureKey12345678901234567890

# ======================
# CLOUDINARY
# ======================

cloudinary.cloud-name=dcphgmd8y
cloudinary.api-key=765359919187239
cloudinary.api-secret=ii88HjGp6emXbbQ3MMhuY33HUk0