# ======================
# DATABASE (SUPABASE)
# ======================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# ======================
# HIKARI
# ======================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ======================
# JPA
# ======================
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ======================
# SERVER
# ======================

server.port=${PORT:8080}

# ======================
# JWT
# ======================

jwt.secret=${JWT_SECRET}

# ======================
# CLOUDINARY
# ======================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}




#Add these in Render Dashboard:
#SPRING_PROFILES_ACTIVE=prod
#
#DB_URL=jdbc:postgresql://db.xxxxx.supabase.co:5432/postgres?sslmode=require
#DB_USERNAME=postgres
#DB_PASSWORD=YOUR_SUPABASE_PASSWORD
#
#JWT_SECRET=YOUR_LONG_SECRET_KEY
#
#CLOUDINARY_CLOUD_NAME=dcphgmd8y
#CLOUDINARY_API_KEY=YOUR_API_KEY
#CLOUDINARY_API_SECRET=YOUR_API_SECRET

#DB_URL=jdbc:postgresql://db.hwalggrjorwerufpsomi.supabase.co:5432/postgres?sslmode=require
#
#DB_USERNAME=postgres
#
#DB_PASSWORD=YOUR_ACTUAL_SUPABASE_PASSWORD